### ISSUE TITLE
tskit 0.4 seems to be breaking tszip tests

### ISSUE THREAD

**Issue by brianzhang01** [tskit-dev/tszip#57] opened 2022-01-24 20:15 UTC
The tszip tests were passing on Nov 8, 2021. Then sometime between then and Jan 20, 2022, they began failing. Here's the latest CI runs, showing 46 failing tests.

https://app.circleci.com/pipelines/github/tskit-dev/tszip/102/workflows/085bcc06-8109-4b39-b907-4ab8047524ff/jobs/104

During that window, tskit 0.4 was released: https://pypi.org/project/tskit/#history.

I ran some things locally that seem to suggest that tszip 0.2.0 works fine with tskit 0.3.7, but not with tskit 0.4.0. Therefore, I'm pinpointing it on some changes in tskit 0.4. For now, I'll just stick to tskit 0.3.7 until this is resolved.

**Comment by molpopgen** [comment] 2022-01-24 23:20
This is #54, I think.

**Comment by brianzhang01** [comment] 2022-01-25 00:03
Yes you're right, sorry about that.

**Comment by molpopgen** [comment] 2022-01-25 03:12
> Yes you're right, sorry about that.

No worries.

**Comment by jeromekelleher** [comment] 2022-01-25 08:42
Thanks for the report @brianzhang01 - yes this is a dupe of #54, so going to close.

**Closed by jeromekelleher** 2022-01-25 08:42 UTC
